version: '3.8'


services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql@14/data/
      - ./script/create_db_dev.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

volumes:
  pgdata:
    driver: local
